name: Sequence Compressor Build and Test

on:
  push:
    branches: ['MohsenBg']
  pull_request:
    branches: ['MohsenBg']

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        run: |
          rustup update
          rustup component add clippy
          rustup install nightly

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - name: Build
        run: |
          cd MohsenBg/sequence_compressor/rust &&
          cargo build --verbose

      - name: Run Sequence Compressor Tests
        run: |
          cd MohsenBg/sequence_compressor/rust &&
          cargo test --verbose -- --test-threads=1
